### ISSUE TITLE
make our own xrootd "cache"

### ISSUE THREAD

**Issue by aminnj** [aminnj/ProjectMetis#15]
build in some feature to either run or print out commands like

xrdcp -S 4 -p root://cmsxrootd.fnal.gov//store/data/Run2017F/HTMHT/MINIAOD/31Mar2018-v1/20000/18333CC3-2140-E811-AC38-3417EBE64762.root  /hadoop/cms/store/user/namin/xrootd/data/Run2017F/HTMHT/MINIAOD/31Mar2018-v1/20000/18333CC3-2140-E811-AC38-3417EBE64762.root

Then another feature to replace /store/ with /store/user/namin/xrootd/ in the DBS file paths when submitting to speed up completion of tail jobs due to xrootd errors.

**Comment by jkguiang** [comment]
We now have a growing US-CMS caching infrastructure, probably making this feature request obsolete; e.g. there's currently a "NanoAOD XCache" that has the capacity to cache all of Nano.
