### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by sgnoohc** [aminnj/ProjectMetis#21]
Can we swap the order of status bar and dataset name so that it looks more like Metis Dashboard? while at it also add the tags.

**Comment by aminnj** [comment]
Solved by https://github.com/aminnj/ProjectMetis/commit/98de03949ae84d40389da3d128b37285b4754612 and https://github.com/aminnj/ProjectMetis/commit/a9d187726f414f093521e4061474e60490f3fd60
